apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    enviroment: lorena
  name: podyam
spec:
  containers:
  - image: nginx
    name: podyam
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
