apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    enviroment: lorena
  name: podyam
spec:
  containers:
  - image: nginx
    name: podyam
    volumeMounts:
      - mountPath: "/scratch"
        name: my-volume
    resources: {}
  volumes:
    - name: my-volume
      emptyDir:
        sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
